import{a as b,i as d,S as p}from"./assets/vendor-483db976.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",a={key:"42137546-386b5be41212ccd429cab5a80",image_type:"photo",orientation:"horizontal",safeSearch:!0,per_page:15,q:void 0,page:1};async function y(r="flower",o=20){return a.q=r,a.page=o,b.get(v,{params:{...a,page:o,q:r}})}const F="/goit-js-hw-12/assets/iconClose-75a7952d.svg",L="/goit-js-hw-12/assets/iconSuccess-55aec323.svg",S="/goit-js-hw-12/assets/iconWarning-75a3a476.svg",u={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageSize:"16px",messageLineHeight:"24px"};function g(r){d.show({message:r,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",iconUrl:F,...u})}function w(r){d.show({message:r,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",iconUrl:L,...u})}function $(r){d.show({message:r,backgroundColor:"#FFA500",progressBarColor:"#708090",iconUrl:S,...u})}const m="gallery-link";function f({largeImageURL:r,tags:o,webformatURL:n,likes:i,views:e,comments:t,downloads:l}){return`<a href="${r}" class="${m}">
    <figure>
     <img src="${n}" alt="${o}" class="gallery-image">
     <figcaption class="gallery__figcaption">
       <div class="image-item">Likes <span class="image-elem">${i}</span></div>
       <div class="image-item">Views <span class="image-elem">${e}</span></div>
       <div class="image-item">Comments <span class="image-elem">${t}</span></div>
       <div class="image-item">Downloads <span class="image-elem">${l}</span></div>
  </figcaption>
  </figure>
  </a>
  `}const q=document.querySelector(".gallery"),E=document.querySelector(".search-form"),x=document.querySelector(".loader"),A=document.querySelector(".loader-scroll"),s={galleryContainer:q,searchForm:E,loaderContainer:x,loaderScrollContainer:A};let h,c;const C=new IntersectionObserver(O,{threshold:0});s.searchForm.addEventListener("submit",async function(r){if(r.preventDefault(),a.q=r.target.elements.query.value,a.q!==""){s.galleryContainer.innerHTML="",s.loaderContainer.style.display="block";try{a.page=1;const{data:{hits:o,totalHits:n}}=await y(a.q,a.page);if(Array.isArray(o)&&o.length>0){const i=o.map(f).join("");s.galleryContainer.innerHTML+=i,new p(`.${m}`).refresh(),c=s.galleryContainer.children[s.galleryContainer.children.length-1],C.observe(c),h=n,w(`Was found: ${n} images`)}else g("Sorry, there are no images matching your search query. Please try again!")}catch(o){g(`Error fetching images: ${o}`)}finally{s.searchForm.reset(),s.loaderContainer.style.display="none"}}});async function O(r){const o=r[0];if(Math.ceil(h/a.per_page)<=a.page)return $("We're sorry, but you've reached the end of search results.");if(o.isIntersecting){s.loaderScrollContainer.style.display="block",a.page++;try{const{data:{hits:n}}=await y(a.q,a.page);if(Array.isArray(n)&&n.length>0){const i=n.map(f).join("");s.galleryContainer.innerHTML+=i,new p(`.${m}`).refresh(),c=s.galleryContainer.children[s.galleryContainer.children.length-1],C.observe(c)}}catch(n){g(`Error loading images: ${n.message}`)}finally{s.loaderScrollContainer.style.display="none"}}}
//# sourceMappingURL=commonHelpers.js.map
